[workspace]
resolver = "2"
members = [
    # Verify
    "verify",
    "verify/macros",
    "benchmark",

    # Frontend
    "frontend/annotator",
    "frontend/substrate3",
    "frontend/core",

    # Backend
    "backend",
    "backend/engine",
    "backend/cells",
    "backend/constraints",
    "backend/placement",
    "backend/routing",

    # Tools
    "tools/visualizer",
]
