[package]
name = "pnr-routing"
version = "0.1.0"
edition = "2021"

[dependencies]
pnr-engine = { path = "../engine" }
pnr-placement = { path = "../placement" }
pnr-cells = { path = "../cells" }
pnr-constraints = { path = "../constraints" }

[dev-dependencies]
pnr-core = { path = "../../frontend/core" }
